In [13]:
#TensorFlow - Classification

import pandas as pd
import tensorflow as tf

In [11]:
#데이터 준비
Iris = pd.read_csv('iris.csv')
Iris = pd.get_dummies(Iris)

Iris.head()

독립 = Iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = Iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(독립.shape, 종속.shape)


(150, 4) (150, 3)


In [14]:
#모델의 구조 생성

X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy')

In [16]:
#데이터로 모델 학습(FIT)
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)


Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0988
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0992
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0990
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0989
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0991
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0991
Epoch 7/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0988
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0988
Epoch 9/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0988
Epoch 10/10
5/5 [==============================] - 0s 5ms/step - loss: 0.0988


In [18]:
#모델 이용
print("Predictions: ", model.predict(독립[0:5]))

Predictions:  [[9.9996650e-01 3.3460612e-05 8.9513241e-12]
 [9.9977845e-01 2.2159949e-04 2.2759500e-10]
 [9.9991000e-01 9.0010042e-05 6.4145814e-11]
 [9.9959582e-01 4.0423809e-04 6.3960781e-10]
 [9.9997234e-01 2.7679891e-05 6.8923287e-12]]
